site_name: Abhinav's notes
site_description: notes about random things
copyright: Made with ❤️ by Abhinav.
repo_name: abhinavmarwaha/notes
repo_url: https://github.com/abhinavmarwaha/notes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
  font:
    text: Inter
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abhinavmarwaha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/abhinav_marwaha
nav:
  - Home: index.md
  - Java:
    - java/intro.md
    - java/oops.md
    - java/helloworld.md
    - java/basics.md
    - java/classes.md
    - java/inheritance.md
    - java/interfaces.md
    - java/annotations.md
    - java/strings.md
    - java/exceptions.md
    - java/collections.md
    - java/generics.md
    - java/java9&beyond.md
    - java/numbers.md
    - java/packages.md
  - Php:
    - php/intro.md
    - php/basics.md
    - php/security.md
  - DS:
    - Array:
      - ds/array/intro.md
      - ds/array/vs-pointers.md
      - ds/array/multi-dimensional.md
      - ds/array/vectors.md
      - ds/array/functions.md
      - ds/array/decay.md
      - ds/array/frequency.md
      - ds/array/min-max.md
      - ds/array/reverse.md
    - Linked List:
      - ds/linked-list/intro.md
      - ds/linked-list/vs-array.md
      - ds/linked-list/count.md
      - ds/linked-list/search.md
      - ds/linked-list/insertion.md
      - ds/linked-list/deletion.md
      - ds/linked-list/functions.md
      - ds/linked-list/generic.md
      - ds/linked-list/swap.md
      - ds/linked-list/reverse.md
      - ds/linked-list/cll.md
      - ds/linked-list/dll.md
      - ds/linked-list/xor-dll.md
      - ds/linked-list/bin-tree-cdll.md
    - Stack:
      - ds/stack/intro.md
      - ds/stack/reverse.md
      - ds/stack/sort.md
      - ds/stack/using-queue.md
      - ds/stack/medium-special.md
      - ds/stack/min-special.md
      - ds/stack/stock-span.md
      - ds/stack/k-stacks.md
    - Queue:
      - ds/queue/intro.md
      - ds/queue/using-stack.md
      - ds/queue/dequeue.md
      - ds/queue/priority-queue.md
      - ds/queue/print-binary.md
    - String:
      - ds/string/intro.md
      - ds/string/string-to-no.md
      - ds/string/reverse.md
      - ds/string/rotation.md
      - ds/string/duplicate.md
      - ds/string/remove-duplicates.md
      - ds/string/frequency.md
      - ds/string/white-space.md
    - Set & Map:
      - ds/set-map/set.md
      - ds/set-map/multiset.md
      - ds/set-map/set-types.md
      - ds/set-map/map.md
    - Tree:
      - ds/tree/intro.md
      - ds/tree/binary-tree.md
      - ds/tree/bt-insertion.md
      - ds/tree/bt-deletion.md
      - ds/tree/bt-height.md
      - ds/tree/traversal.md
      - ds/tree/bt-level-order.md
      - ds/tree/bt-enumeration.md
      - ds/tree/bt-search.md
      - ds/tree/bt-swap-nodes.md
      - ds/tree/k-smallest.md
      - ds/tree/lowest-common-ancestor.md
      - ds/tree/bst.md
      - ds/tree/bst-check.md
      - ds/tree/bst-merge.md
      - ds/tree/handshaking-lemma.md
      - ds/tree/segment-tree.md
    - Graph:
      - ds/graph/intro.md
      - ds/graph/bfs.md
      - ds/graph/dfs.md
      - ds/graph/dfs-disconnected.md
    - Heap:
      - ds/heap/intro.md
      - ds/heap/heap-sort.md
      - ds/heap/fibonacci-heap.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details
  - footnotes
