site_name: Abhinav's notes
site_description: notes about random things
copyright: Made with ❤️ by Abhinav.
repo_name: abhinavmarwaha/notes
repo_url: https://github.com/abhinavmarwaha/notes
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
  font:
    text: Inter
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true
  # - pdf-export:
  #       verbose: true
  #       media_type: print

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abhinavmarwaha
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/abhinav_marwaha
  manifest: manifest.webmanifest
nav:
  - Home: index.md
  - AI:
    - ai/intro.md
    - ai/intelligence.md
    - ai/history.md
    - ai/subjects.md
    - ai/fields.md
    - ai/agents.md
    - ai/environment.md
    - ai/tasks.md
    - ai/technique.md
    - ai/search.md
    - ai/constraint-satisfaction.md
    - ai/game-playing.md
    - ai/means-ends.md
  - Java:
    - java/intro.md
    - java/oops.md
    - java/hello.md
    - java/basics.md
    - java/classes.md
    - java/inheritance.md
    - java/interfaces.md
    - java/annotations.md
    - java/strings.md
    - java/re.md
    - java/exceptions.md
    - java/collections.md
    - java/generics.md
    - java/numbers.md
    - java/packages.md
    - java/io.md
    - java/concurrency.md
    - java/networking.md
    - java/jaxb.md
    - java/json.md
    - java/security.md
    - java/debugging.md
    - java/deployment.md
    - java/jdbc.md
    - java/garbage-collection.md
    - java/java9-beyond.md
    - java/platform.md
    - java/jsp.md
    - java/i18n.md
  - Php:
    - php/intro.md
    - php/basics.md
    - php/security.md
  - DS:
    - Array:
      - ds/array/intro.md
      - ds/array/vs-pointers.md
      - ds/array/multi-dimensional.md
      - ds/array/vectors.md
      - ds/array/functions.md
      - ds/array/decay.md
      - ds/array/frequency.md
      - ds/array/min-max.md
      - ds/array/reverse.md
    - Linked List:
      - ds/linked-list/intro.md
      - ds/linked-list/vs-array.md
      - ds/linked-list/count.md
      - ds/linked-list/search.md
      - ds/linked-list/insertion.md
      - ds/linked-list/deletion.md
      - ds/linked-list/functions.md
      - ds/linked-list/generic.md
      - ds/linked-list/swap.md
      - ds/linked-list/reverse.md
      - ds/linked-list/cll.md
      - ds/linked-list/dll.md
      - ds/linked-list/xor-dll.md
      - ds/linked-list/bin-tree-cdll.md
    - Stack:
      - ds/stack/intro.md
      - ds/stack/reverse.md
      - ds/stack/sort.md
      - ds/stack/using-queue.md
      - ds/stack/medium-special.md
      - ds/stack/min-special.md
      - ds/stack/stock-span.md
      - ds/stack/k-stacks.md
    - Queue:
      - ds/queue/intro.md
      - ds/queue/using-stack.md
      - ds/queue/dequeue.md
      - ds/queue/priority-queue.md
      - ds/queue/print-binary.md
    - String:
      - ds/string/intro.md
      - ds/string/string-to-no.md
      - ds/string/reverse.md
      - ds/string/rotation.md
      - ds/string/duplicate.md
      - ds/string/remove-duplicates.md
      - ds/string/frequency.md
      - ds/string/white-space.md
    - Set & Map:
      - ds/set-map/set.md
      - ds/set-map/multiset.md
      - ds/set-map/set-types.md
      - ds/set-map/map.md
    - Tree:
      - ds/tree/intro.md
      - ds/tree/binary-tree.md
      - ds/tree/bt-insertion.md
      - ds/tree/bt-deletion.md
      - ds/tree/bt-height.md
      - ds/tree/traversal.md
      - ds/tree/bt-level-order.md
      - ds/tree/bt-enumeration.md
      - ds/tree/bt-search.md
      - ds/tree/bt-swap-nodes.md
      - ds/tree/k-smallest.md
      - ds/tree/lowest-common-ancestor.md
      - ds/tree/bst.md
      - ds/tree/bst-check.md
      - ds/tree/bst-merge.md
      - ds/tree/handshaking-lemma.md
      - ds/tree/segment-tree.md
    - Graph:
      - ds/graph/intro.md
      - ds/graph/bfs.md
      - ds/graph/dfs.md
      - ds/graph/dfs-disconnected.md
    - Heap:
      - ds/heap/intro.md
      - ds/heap/heap-sort.md
      - ds/heap/fibonacci-heap.md
  - Algo:
    - algo/glossary.md
    - Analysis:
      - algo/analysis/intro.md
      - algo/analysis/space.md
      - algo/analysis/classes.md
      - algo/analysis/examples.md
      - algo/analysis/lower-upper-bound-theory.md
      - algo/analysis/master-theorum.md
      - algo/analysis/recursive.md
      - algo/analysis/amortised.md
      - algo/analysis/pseudo-polynomial.md
      - algo/analysis/caching.md
      - algo/analysis/graph-coloring.md
    - Search:
      - algo/search/intro.md
      - algo/search/binary.md
      - algo/search/ternery.md
      - algo/search/exponential.md
      - algo/search/interpolation.md
      - algo/search/jump.md
    - Sort:
      - algo/sort/intro.md
      - algo/sort/bubble.md
      - algo/sort/insertion.md
      - algo/sort/merge.md
      - algo/sort/quick.md
      - algo/sort/merge-quick.md
      - algo/sort/selection.md
      - algo/sort/topological.md
      - algo/sort/counting.md
    - Divide & Conquer:
      - algo/dac/intro.md
      - algo/dac/median.md
      - algo/dac/min-max.md
      - algo/dac/power.md
      - algo/dac/strassen-mul.md
      - algo/dac/closest-pair.md
      - algo/dac/count-inversion.md
    - DP:
      - algo/dp/intro.md
      - algo/dp/power.md
      - algo/dp/knapsack.md
    - Branch & Bound:
      - algo/branch-bound/intro.md
      - algo/branch-bound/knapsack.md
    - Greedy:
      - algo/greedy/intro.md
      - algo/greedy/jobs.md
      - algo/greedy/activities.md
      - algo/greedy/min-coins.md
      - algo/greedy/min-platform.md
      - algo/greedy/dijkstra.md
      - algo/greedy/huffman-coding.md
      - algo/greedy/improved-huffman.md
      - algo/greedy/mst-prim.md
      - algo/greedy/mst-kruskal.md
    - Graph:
      - algo/graph/cycle-detection.md
    - Hashing:
      - algo/hashing/intro.md
      - algo/hashing/union-intersection.md
      - algo/hashing/subset-array.md
      - algo/hashing/kdistance-duplicate.md
      - algo/hashing/itinerary-tickets.md
      - algo/hashing/sum-2-array.md
      - algo/hashing/tree-print-vertical.md
      - algo/hashing/java-hashing.md
    - algo/maths.md
    - algo/bits.md
    - algo/misc/automata.md
    - algo/misc/locallity.md
    - algo/misc/recursion.md
    - algo/misc/segmentation-fault.md
    - algo/misc/swap.md
  - Networking:
    - networking/setup.md
  - TOC:
    - toc/automata.md
  - web.md
  - google-fu.md
  - no-code.md

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.details
  - footnotes